name: GitBook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://gitbook/gitbook-cli:latest
        with:
          args: "gitbook install && gitbook build && gitbook pdf && gitbook epub && mv _book docs && cp CNAME docs"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gitbook